[package]
name = "map-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
noise = "0.9.0"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
